name: "BurkingArmazem"
api: []
version: "1.5"
api-version: 1.13
depend: [WorldGuard, WorldEdit, BurkingExtraFlags]
main: me.joao.armazem.principal.Main
commands:
    armazem:
      description: comando principal